### ISSUE TITLE
ApplicationInsights input

### ISSUE THREAD

**Issue by Doomblaster** [Azure/diagnostics-eventflow#165]
Hi,

I'm trying to utilize the ApplicationInsights input in an on-premise service fabric dotnet core service. When creating a pipeline I get the following exception:
DiagnosticPipelineFactory: item of type 'ApplicationInsights' could not be created
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Diagnostics.EventFlow.Inputs.ApplicationInsights, Version=1.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
File name: 'Microsoft.Diagnostics.EventFlow.Inputs.ApplicationInsights, Version=1.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
The Zone of the assembly that failed was:
MyComputer
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.ProcessSection[PipelineItemType,PipelineItemChildType](IConfigurationSection configurationSection, IHealthReporter healthReporter, IDictionary`2 itemFactories, IDictionary`2 childFactories, String childSectionName)

I know I havent't added the &lt;TelemetryProcessors&gt; in any config (not sure if I need to add it, since service fabric seems to provider this magically), but I think this error is related to something fishy with the nuget package.

**Comment by karolz-ms** [comment]
OOPS, sorry. I can see why it is happening--this assembly was inadvertently excluded from the signing process. Will publish a new version shortly!

**Comment by karolz-ms** [comment]
Should be fixed now (get AI input package version 1.1.1 or newer, please)
