### ISSUE TITLE
Azure Service Fabric: Errors on node when using RunAs User policy & non local admin

### ISSUE THREAD

**Issue by knowhoper** [Azure/diagnostics-eventflow#186]
Hi,

When using EventFlow on a remote cluster and the `<RunAsPolicy CodePackageRef="Code" UserRef="SqlUser" /> `construct in the ApplicationManifest.xml; I get the following error.

> The object is closed.    at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
>    at System.Fabric.Interop.Utility.WrapNativeSyncInvoke(Action action, String functionTag, String functionArgs)
>    at System.Fabric.Interop.Utility.RunInMTA(Action action)
>    at System.Fabric.FabricClient.HealthClient.ReportHealth(HealthReport healthReport)
>    at Microsoft.Diagnostics.EventFlow.ServiceFabric.ServiceFabricHealthReporter.ReportMessage(HealthState healthState, String description)
>    at Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.ReportItemCreationFailedAndThrow(IHealthReporter healthReporter, String itemType, Exception e)
>    at Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.ProcessSection[PipelineItemType,PipelineItemChildType](IConfigurationSection configurationSection, IHealthReporter healthReporter, IDictionary`2 itemFactories, IDictionary`2 childFactories, String childSectionName)
>    at Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.CreatePipeline(IConfiguration configuration, IHealthReporter healthReporter)
>    at Program.Main() in C:\dev\Service\Program.cs:line 21

This translates to an error on the line: 

`using (diagnosticsPipeline = ServiceFabricDiagnosticPipelineFactory.CreatePipeline("AcmeService"))`

This error does not appear if the account named in the RunAs policy is a member of the LocalAdministrators group on the node. This is not an ideal security group for our user though. 

Can anyone help?

Thanks in advance.

**Comment by karolz-ms** [comment]
@knowhoper how is the `SqlUser` declared? What groups does it belong to?

@oanapl Are there any special security requirements to call `ReportHealth`?

**Comment by oanapl** [comment]
FabricClient must be configured with admin privileges with the cluster to allow health reporting. Otherwise, you can report through Partition and CodePackageActivationContext from inside the service itself. Read [more](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-how-to-report-and-check-service-health).
If the FabricClient inside Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.ServiceFabricHealthReporter needs to report health, then is must be configured as admin. Since it runs as the RunAs user, then the RunAs user must have admin privileges.

**Comment by karolz-ms** [comment]
Thanks @oanapl! In EventFlow we are [reporting deployed service package health](https://github.com/Azure/diagnostics-eventflow/blob/master/src/Microsoft.Diagnostics.EventFlow.ServiceFabric/ServiceFabricHealthReporter.cs#L62) so it sounds like we can just report pretty much the same information through `CodePackageActivationContext` and that would not require admin privileges. Did I get it right?

**Comment by oanapl** [comment]
Yes, that's correct. 
CodePackageActivationContext limits you to report only on your app, so we allow it.
FabricClient allows you to report on any entity in the cluster, so it must have Admin privileges to avoid one app reporting badly on another app/entity.

**Comment by karolz-ms** [comment]
Cool, thx. @knowhoper fix is on the way, will let you know when it is available on nuget.org

**Comment by knowhoper** [comment]
Thanks a lot guys!

**Comment by karolz-ms** [comment]
OK, @knowhoper pleas try EF.ServiceFabric nuget package version 1.2.1, published earlier today and let me know if it solves the problem. Thx!
