### ISSUE TITLE
Error handling problem

### ISSUE THREAD

**Issue by BuddhaBuddy1** [Azure/diagnostics-eventflow#215]
Several minutes after installing our application, we are getting a health warning (and no logging):

```
ElasticSearchOutput: diagnostics data upload has failed.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Elasticsearch.Net.RequestPipeline.CreateClientException[TResponse](TResponse response, IApiCallDetails callDetails, RequestData data, List`1 pipelineExceptions) in c:\Projects\elastic\net-6\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 502
   at Elasticsearch.Net.Transport`1.FinalizeResponse[TResponse](RequestData requestData, IRequestPipeline pipeline, List`1 seenExceptions, TResponse response) in c:\Projects\elastic\net-6\src\Elasticsearch.Net\Transport\Transport.cs:line 174
   at Elasticsearch.Net.Transport`1.d__15`1.MoveNext() in c:\Projects\elastic\net-6\src\Elasticsearch.Net\Transport\Transport.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nest.ElasticClient.d__271`4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Diagnostics.EventFlow.Outputs.ElasticSearchOutput.d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Diagnostics.EventFlow.Outputs.ElasticSearchOutput.d__6.MoveNext()
```

It looks like an problem in error handling. The first check on callDetails is throwing NullReferenceException. Later calls on that object use callDetails?, so it is known that it could be null, but the very first check doesn't take that into account.

Our actual error (possibly a configuration problem in Elastic Search) is being obscured by the problem in error handling.

**Comment by karolz-ms** [comment]
@BuddhaBuddy1  looks like [this change](https://github.com/elastic/elasticsearch-net/pull/3101) has fixed this on the Elasticsearch.Net side. On the EventFlow side we should take a dependency on the fixed package version, but in the meantime just try upgrading to NEST & Elasticsearch.Net version 6.1.0

**Comment by karolz-ms** [comment]
@BuddhaBuddy1 the implementation is using [SniffingConnectionPool](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/connection-pooling.html#sniffing-connection-pool) under the covers; maybe it is sniffing something bad :-) (misconfiguration).

Glad you are making progress, but let's keep this issue open as a reminder for myself that we need to take a dependency on 6.1.0 from EventFlow ES output

**Comment by karolz-ms** [comment]
@BuddhaBuddy1 try ElasticSearch output package version 2.5.1--I have just pushed it to NuGet. By default it should have the sniffing connection pooling disabled and should work for you, but please confirm/deny.

**Comment by karolz-ms** [comment]
TODO: update ES output to depend on Elasticsearch.NET 6.1.0

**Comment by karolz-ms** [comment]
Nuget package 2.5.2 has been published
