### ISSUE TITLE
Microsoft.Extensions.Logging input factory namespace issue.

### ISSUE THREAD

**Issue by JimPaine** [Azure/diagnostics-eventflow#31]
When trying to use the Microsoft.Extensions.Logging input factory I found that I had to install 
"Microsoft.Diagnostics.EventFlow.Inputs.MicrosoftLogging" rather than "Microsoft.Diagnostics.EventFlow.Inputs.Microsoft.Extensions.Logging" as specified in the read me. Then at run time I found that the DiagnosticsPipelineFactory was falling over when trying to reflect on "Microsoft.Diagnostics.EventFlow.Inputs.Microsoft.Extensions.Logging"

> DiagnosticPipelineFactory: item of type 'Microsoft.Extensions.Logging' could not be created
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Diagnostics.EventFlow.Inputs.Microsoft.Extensions.Logging, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Diagnostics.EventFlow.Inputs.Microsoft.Extensions.Logging, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.ProcessSection[PipelineItemType,PipelineItemChildType](IConfigurationSection configurationSection, IHealthReporter healthReporter, IDictionary`2 itemFactories, IDictionary`2 childFactories, String childSectionName)

I have made a [change](https://github.com/JimPaine/diagnostics-eventflow/commit/0fceeed82413b2c106d6c6d6c1782c307f58ebee#diff-04c6e90faac2675aa89e2176d2eec7d8) and am happy to raise a pull request, but wanted to check which namespace you were looking to use.

**Comment by lmolkova** [comment]
Thanks for fixing it. Please submit PR for your change, DLL names in your change are correct and input type should remain "Microsoft.Extensions.Logging".

**Comment by karolz-ms** [comment]
Thank you for helping with this, Jim! 

Resolved with https://github.com/Azure/diagnostics-eventflow/pull/32
New Nuget package (1.0.1) will be published shortly
