### ISSUE TITLE
AzureMonitorLogs Output and ServiceFabric configuration

### ISSUE THREAD

**Issue by berndku** [Azure/diagnostics-eventflow#321]
After switching from OmsOutput to AzureMonitorLogs we see the following exception: 
```

System.Exception: 'DiagnosticPipelineFactory: item of type 'AzureMonitorLogs' could not be created
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Microsoft.Diagnostics.EventFlow.Outputs.OmsOutput.CreateConnectionData(OmsOutputConfiguration configuration)
   at Microsoft.Diagnostics.EventFlow.Outputs.OmsOutput..ctor(IConfiguration configuration, IHealthReporter healthReporter)
   at Microsoft.Diagnostics.EventFlow.Outputs.OmsOutputFactory.CreateItem(IConfiguration configuration, IHealthReporter healthReporter)
   at Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.ProcessSection[PipelineItemType,PipelineItemChildType](IConfigurationSection configurationSection, IHealthReporter healthReporter, IDictionary`2 itemFactories, IDictionary`2 childFactories, String childSectionName)'
```

The output configuration looks like this: 
```
 "outputs": [
    {
      "type": "AzureMonitorLogs",
      "workspaceId": "servicefabric:/OMS/WorkspaceId",
      "workspaceKey": "servicefabric:/OMS/WorkspaceKey",
      "logTypeName": "EventFlow"
    }
  ],
```

If we write workspaceId und workspaceKey directly into the eventFlowConfig.json file, it works, but we need to keep this information out the config. 

Does the AzureMonitorLogs Output no longer support service fabric config references ?

**Comment by karolz-ms** [comment]
The change to `AzureMonitorLogs` should not affect the ability to load values from Service Fabric configuration files. Can you double-check that you are still using `ServiceFabricDiagnosticPipelineFactory`? The logic to read Service Fabric configuration files is there.

**Comment by berndku** [comment]
Yes, still using _ServiceFabricDiagnosticPipelineFactory_

**Comment by karolz-ms** [comment]
Could you please share a Visual Studio project that demonstrates the problem?

**Comment by berndku** [comment]
The root cause of the problem was in our code. There was a hidden section, that was overriding the configuration during runtime and we had to enhance it to deal with AzureMonitorLogs output. Sorry for this and many thanks for your help!

**Comment by karolz-ms** [comment]
No problem. Glad it is working for you ☺️
