### ISSUE TITLE
ElasticSearchOutput failed to send health data

### ISSUE THREAD

**Issue by Zhichao-Hong** [Azure/diagnostics-eventflow#61]
Trying to send logs from service fabric to elasticsearch (setup using the documentation from: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostic-how-to-use-elasticsearch).  Followed through the instruction and try to send log from service fabric.  Got the following exceptions:

...
ElasticSearchOutput: diagnostics data upload has failed.
System.ArgumentException: Value does not fall within the expected range.
   at System.Fabric.Interop.NativeClient.IFabricHealthClient3.ReportHealth(IntPtr healthReport)
   at System.Fabric.FabricClient.HealthClient.ReportHealthHelper(HealthReport healthReport)
   at System.Fabric.Interop.Utility.<>c__DisplayClass13.b__12()
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
   at System.Fabric.Interop.Utility.RunInMTA(Action action)
   at System.Fabric.FabricClient.HealthClient.ReportHealth(HealthReport healthReport)
   at Microsoft.Diagnostics.EventFlow.ServiceFabric.ServiceFabricHealthReporter.ReportMessage(HealthState healthState, String description)
   at Microsoft.Diagnostics.EventFlow.Outputs.ElasticSearchOutput.ReportEsRequestError(IResponse response, String request)
   at Microsoft.Diagnostics.EventFlow.Outputs.ElasticSearchOutput.d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Diagnostics.EventFlow.Outputs.ElasticSearchOutput.d__6.MoveNext()

The same set up works without an issues in an local cluster.  ElasticSearch version is 5.1.1.  Eventflow is the using the latest version 1.1.0.

**Comment by karolz-ms** [comment]
@Zhichao-Hong what is the version of Service Fabric runtime on the remote cluster?

BTW, I would recommend to ensure you use Microsoft.EventFlow.ServiceFabric Nuget package version 1.1.1 or later (although it probably won't help with the issue you encountered)

**Comment by Zhichao-Hong** [comment]
Service Fabric Version: 5.4.164.9494

I debugged a little further.  Now the problem is due to documentation bug about the configuration.  In the ElasticSearch Output section, the example given is using:
```
{
    "type": "ElasticSearch",
    "indexNamePrefix": "app1-",
    "serviceUri": "https://myElasticSearchCluster:9200",
    "basicAuthenticationUserName": "esUser1",
    "basicAuthenticationPassword": "<MyPassword>",
    "eventDocumentTypeName": "diagData"
}
```
The basicAuthenticationPassword should be spelled as _**basicAuthenticationUserPassword**_ (found this in the source code).  Also, when using the Uri with port number (:9200), it ignores the username and password.  So when the elasticsearch 9200 port is open to remote, the configuration will work.  But when using the Uri without port (via http url mapping, eg http://myespip/elasticsearch", the username and password is enforced.  But in the case, since I was using the wrong key for the password, the ElasticSearchOutput took the password as empty or null.  So the connection failed.  The error message from NEST is confusing.

**Comment by karolz-ms** [comment]
Thanks @Zhichao-Hong, I have updated the documentation.

BTW you should have received a health warning that your credentials are incomplete in this situation. Maybe it was overridden by the later errors?

When you say that Uri containing specific port cause credentials to be ignored, how did you determine that? Are you saying it is an EventFlow bug, NEST bug or ES bug?

**Comment by karolz-ms** [comment]
Closing this for now--feel free to reopen if you need us to look more closely
